[[casacorewrapper]]
arch = "aarch64"
git-tree-sha1 = "05ac178cbe7bdb418009d697d5451284857b7812"
os = "macos"

    [[casacorewrapper.download]]
    sha256 = "43f74420a9d155035a7e387b8077185167df4cf4b59bd35934432b5d11aa9fa3"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.aarch64-apple-darwin.tar.gz"
[[casacorewrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18e8f7f1ef51b40162715cad92c5c11f01a5f730"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "668870cbc05f2cf2dea5c6fd8e3f90545af5e3dbd8b36acffacb9e9e9a21f274"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[casacorewrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "073909752b2a4dc07a31771ec5fbca477b1dca80"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "ebf2c0666b167dbb5fcf186d335d64a544a6630544650d77594d43b360ccaf23"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[casacorewrapper]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c6ec19a873f93eb9af23c6261316778f4482d67"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "46f16f53c86192f76f2cdba776a567f42f6ac6066e67143d0f727d325522f545"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[casacorewrapper]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "294fb01c5ed5e4438557162d75257248e654360c"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "9bec2738389cb1a85a3804e119317ea8dc9bfa95238cad67b0c88226a23f5a51"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[casacorewrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5020baec0e10502a70cb4490b2fda80311664e6"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "57a6cdc5ec3c2aae7a0b8096c91b2860fad33d5613dbb11a470f7fb54f6dd336"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[casacorewrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9787ec6df032a3c25316f759e6c48b633cce042a"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "d4113e0b68ea51d25fea63891dcf2c81187d1b7263bfdec4ba34b17d6b096a94"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[casacorewrapper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db844b94e3ac4bafca420c49a10daf8a46650fa8"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "eac016d882ed3e4e0b76387ba64dcb23599ce9eb47a751e3c6741efca2e8c848"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.i686-linux-gnu-cxx03.tar.gz"
[[casacorewrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3aa77c199f502838c2c6d3f2833d72f6b2cc77c8"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "94e4254007b6f422da516874ad011af4137f864a95b618aa6f41aac1d8da6eb9"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.i686-linux-gnu-cxx11.tar.gz"
[[casacorewrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca0ca0fa18f5edf36771f3d83d3bef2a81af66ff"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "f8ecdbc8d24b23abced8920da3efef7cf4babfc7133298f95fbbfc8a25f26310"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[casacorewrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfbc863477e69be747ca58804cc5131c567d8e92"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "1a6f339cbe823deb4a3dc75a372368fb6990f56ca90d331026f18296465db3bf"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[casacorewrapper]]
arch = "x86_64"
git-tree-sha1 = "cd21c196727634933d058b2cd9e431ac4d71a522"
os = "macos"

    [[casacorewrapper.download]]
    sha256 = "ce518e831b9dcfee38871cafe1ddf7a404b94d0bf678c7a7ba59d5b2da15d144"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.x86_64-apple-darwin.tar.gz"
[[casacorewrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f267bdcc1cccc83cde9f18b7102e069ec27ba8a2"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "b14c705a2198ee73412e9c7560389b2f76dbb0abcd3c80cf404d0636eb27446c"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[casacorewrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e146afb5dbbe4e66a935d2c8f7957711a9bba0a3"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "264c6659875257ae5a59b73ce1254c1c0508c6f825cb7032a060b9a41ade36ec"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.1.0+1/casacorewrapper.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
