[[casacorewrapper]]
arch = "aarch64"
git-tree-sha1 = "4e1b7ec0f1dd13c74f25fcc8a073cf01b9ae48ca"
os = "macos"

    [[casacorewrapper.download]]
    sha256 = "2764fb8c432c0a3465d576af355eeaec7c541a94e085d479b521a2c8a1471eb7"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.aarch64-apple-darwin.tar.gz"
[[casacorewrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90d6dfa4e162547a4bb495146174f7c2562e2431"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "83aba84967fddac64fb9c396e619daa348ebd9826607ece45a25f423e5fba4fd"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[casacorewrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06f4a781dfdc8768fbc3a5666a1fd75b53eb2998"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "1e37e2db4a550090f4379e33e0d2d2e5f2e2068c66ae55764266bc3acf5c20ec"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[casacorewrapper]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0c6afbe48218d88f1704887c0bfde86b1f84d86"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "fb8eee60ce1e6b3ace742144cd87a59aff92a7d61ab7fffc755e22fdf65a6ec3"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[casacorewrapper]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "356aa817439ab71a8cd1455c380a40b0b7c66e3d"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "9ca535fa3d0a43bc7c26723bfdc48fd91152015401f0a01270e25580e455daec"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[casacorewrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2ffd30642214db4c30ede0268734630776a9e25"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "bf78750e742fc60572eb4289e61c847aa068ef0fd12304e62c8e78da7a4fc509"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[casacorewrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee01db618eae59632edc74cab1c6c600b6ddf419"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "ba675b774906b3d37783a5e53986db325381ad85790278f479d5f78b409f7727"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[casacorewrapper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7364fe1f1faeea86c22ff95b42417f356f72c786"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "26d089b3c98299d010c6beace7c65ce1a934c21211e3ff6ec99553b88ce35f8b"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.i686-linux-gnu-cxx03.tar.gz"
[[casacorewrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96428ec881f967cc5e33a566bd399f6d5951ca3e"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "5226706cc9402358c3ac59c6d608d9a00a269d89d39120056bad6cd6baa79f64"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.i686-linux-gnu-cxx11.tar.gz"
[[casacorewrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aabf776f88664e33adb497a9f4110384ad613990"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "927c3139b7de47f5e640ebff07a9027a2b31dc26f04528f0186f163576a20bea"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[casacorewrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "420abb40fa53330f28fc85b9f49881a7a180d9f4"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "821b920d64e537e531f7572d32b36228202b9b6817b5607c6a3a57b69202ff7b"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[casacorewrapper]]
arch = "x86_64"
git-tree-sha1 = "36591ff326aa695692479a801987295ef6204875"
os = "macos"

    [[casacorewrapper.download]]
    sha256 = "b6a61d23255f25cabb1d17f130ed58d56d073f6c4fbe7438226a5fd3ffbaa7cb"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.x86_64-apple-darwin.tar.gz"
[[casacorewrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "777aff719ed9b9e5cc92637f098aa5b1106b9154"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "73adc270a740115379020fd1f5b76c34cbb6394f85c15760be47f979e6f6732b"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[casacorewrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a933176e1e6b9e5e0e2dbed05b02f94932f89d1"
libc = "glibc"
os = "linux"

    [[casacorewrapper.download]]
    sha256 = "9bd33081ce854c8a76e508bdfaec1853d72e5051a00062cb97e4c270fc8271ec"
    url = "https://github.com/JuliaBinaryWrappers/casacorewrapper_jll.jl/releases/download/casacorewrapper-v0.2.0+0/casacorewrapper.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
